- hosts: all 
  become: yes
  tasks: 

  - name: Install Apache
    include: apache.yml

  - name: Install php packages 
    include: php.yml

  - name: Install WordPress
    include: wordpress.yml
  
  - name: Install Database
    include: db.yml 