- name: Download WordPress
  ansible.builtin.get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz #changed the filenam to wordpress.tar.gz while downloading because our code should be always usable in case of version changes to wordpress


- name: Extract WordPress
  ansible.builtin.unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /tmp/wordpress/.
    dest: /var/www/html
    owner: www-data
    group: www-data
    mode: '0755'
    remote_src: yes

- name: Remove file 
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent